name: Test Client Application

on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download compiled exe artifact
      uses: actions/download-artifact@v3
      with:
        name: task5_exe
        path: tests/SWtask5/x64/Debug

    - name: Run tests and save output to file
      run: |
        cd tests/SWtask5/x64/Debug
        SWtask5.exe > test_output.txt

    - name: Upload test results as artifact
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: tests/SWtask5/x64/Debug/test_output.txt
