name: Build Client Application

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up MinGW
      run: |
        # Install MinGW (g++) if it's not already available
        choco install mingw

    - name: Build client application
      run: |
        # Set path to client source and output directories
        set CLIENT_APP_PATH=src\SW_Task3\SW_Task3\SW_Task3.cpp
        set CLIENT_BUILD_OUTPUT=Build\SW_Task3_build
        
        if not exist %CLIENT_BUILD_OUTPUT% (
          mkdir %CLIENT_BUILD_OUTPUT%
        )

        # Ensure MinGW is available
        where g++ > nul 2>&1
        if %errorlevel% neq 0 (
          echo "MinGW (g++) not found, please ensure it's installed and added to the system PATH."
          exit /b %errorlevel%
        )

        # Compile the client application
        g++ -o %CLIENT_BUILD_OUTPUT%\SW_Task3.exe %CLIENT_APP_PATH% -lgdi32 -luser32
        if %errorlevel% neq 0 (
          echo "Client application build failed"
          exit /b %errorlevel%
        )
        echo "Client application built successfully!"

    - name: Archive binaries
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: SW_Task3-exe
        path: Build\SW_Task3_build\SW_Task3.exe
