name: Build and Test Client Application

on: [push, pull_request]

jobs:
  test client using googletest:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up MinGW
      run: |
        choco install mingw

    - name: Build client application
      run: |
        # Set path to client source and output directories
        $CLIENT_APP_PATH = "src\SW_Task3\SW_Task3\SW_Task3.cpp"
        $CLIENT_BUILD_OUTPUT = "Build\SW_Task3_build"
  
        # Compile the client application
        g++ -o "$CLIENT_BUILD_OUTPUT\SW_Task3.exe" "$CLIENT_APP_PATH" -lgdi32 -luser32
        
    - name: Build tests
      run: |
        # Set path to test source and output directories
        $TEST_APP_PATH = "tests\SWtask5\SWtask5\test.cpp"
        $TEST_BUILD_OUTPUT = "Build\task5_output"

        # Compile the test executable
        g++ -o "$TEST_BUILD_OUTPUT\task5.exe" "$TEST_APP_PATH" -lgtest -lgtest_main -pthread

    - name: Run tests and save output to XML
      run: |
        cd Build/test_output
        ./test.exe --gtest_output=xml:../test_results.xml  

    - name: Upload test results as artifact
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: Build/task5_output.xml

    - name: Archive binaries
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: SWtask5_exe
        path: Build\task5.exe
